spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      leak-detection-threshold: 15000
      validation-timeout: 5000
      auto-commit: false

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "${spring.application.name}::"

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:true}
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 2s

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:}
    properties:
      security.protocol: ${SPRING_KAFKA_SECURITY_PROTOCOL:}
      sasl.mechanism: ${SPRING_KAFKA_SASL_MECHANISM:}
      sasl.jaas.config: >-
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_SASL.USERNAME}"
        password="${KAFKA_SASL.PASSWORD}";
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,flyway,env
  endpoint:
    health:
      validate-group-membership: true
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,redis,kafka
        liveness:
          include: livenessState
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    otlp:
      tracing:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://tempo.tracing.svc.cluster.local:4318}
  health:
    defaults:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    redis:
      enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO
    org.springframework.cache: INFO
